version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: bayu
        uid: 1000
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  db:
    image: mysql:latest 
    container_name: laravel-db 
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel # this optional, but better to change
      MYSQL_ROOT_PASSWORD: Admin#1234 # make sure you change this, otherwise....
      MYSQL_PASSWORD: Admin#1234  # make sure you change this, otherwise....
      MYSQL_USER: laravel_user # make sure you change this, otherwise....
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel
    
  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
